version: '3'

networks:
  my-network:
    external: true

services:
  
  spark-master:
    image: minhtuyenvp02/spark-cluster-3.3.2
    container_name: spark-master
    #    depends_on:
    #      - cassandra-3
    ports:
      - "9090:8080"
      - "7077:7077"
    #volumes:
    #  - ./kafka_consumer/target:/opt/spark-apps
    #  - ./kafka_consumer/conf/master:/opt/spark/conf
    #  - ./kafka_consumer/src/resource:/opt/spark/data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    networks:
      - my-network
  spark-worker-1:
    image: minhtuyenvp02/spark-cluster-3.3.2
    ports:
      - "29090-29999:8080"
      #      - "9099:8080"
      - "7800:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-1
    networks:
      - my-network
    #volumes:
    #  - ./kafka_consumer/target:/opt/spark-apps
    #  - ./kafka_consumer/conf/worker:/conf
    #  - ./kafka_consumer/src/resource:/opt/spark/data
  spark-worker-2:
    image: minhtuyenvp02/spark-cluster-3.3.2
    ports:
      - "9092:8080"
      - "7801:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-2
    networks:
      - my-network
    #volumes:
    #  - ./kafka_consumer/target:/opt/spark-apps
    #  - ./kafka_consumer/conf/worker:/conf
    #  - ./kafka_consumer/src/resource:/opt/spark/data
  spark-history-server:
    image: rangareddy1988/spark-history-server:3.4.1
    container_name: spark-history-server
    environment:
      - SPARK_HISTORY_UI_PORT=18080
      - SPARK_DAEMON_MEMORY=4g
      - SPARK_HISTORY_RETAINEDAPPLICATIONS=200
      - SPARK_HISTORY_UI_MAXAPPLICATIONS=500
    ports:
      - 18080:18080
      - 4444:4040
      
    networks:
      - my-network
    #volumes:
    #  - /tmp/spark/spark-events:/tmp/spark-events
     # - /tmp/spark/spark-history-server-logs:/var/log/spark